<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="DetailsPizza.aspx.cs" Inherits="LAB_WEB_4.DetailsPizza" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            height: 26px;
        }
        table, th, td {
            border: 1px solid black;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <h1>Detail of the Pizza</h1>
           
               
            <br/>
            <asp:DetailsView ID="dvPizza" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateInsertButton="True" Height="50px" Width="125px" OnModeChanging="dvPizza_ModeChanging1">
                <Fields>
                    <asp:TemplateField>
                        <ItemTemplate>
                            <asp:Image ID="Image1" runat="server" ImageUrl='<%# Eval("PicURL") %>' Height="100" Width="100"/>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Fields>
            </asp:DetailsView>
            <br/><br/>
        </div>
    </form>
</body>
</html>
